version: "3.9"
services:
  web:
    build: ./FastEvents
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    build:
      context: .
      dockerfile: DataBase/Dockerfile
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "FastTeam!2020"
      ACCEPT_EULA: "Y"
